// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRacasCachorro.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260923004147_BancoInicial")]
    partial class BancoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RacaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectativaVidaAnos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Racas");
                });
#pragma warning restore 612, 618
        }
    }
}
